FROM zikalino/python-sdk-dev
MAINTAINER zikalino

RUN git clone https://github.com/Azure/azure-cli
RUN git clone https://github.com/Azure/azure-cli-extensions
RUN git clone https://github.com/Azure/azure-cli-dev-tools


